name: Release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Use Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: build
          prefix: browserviewer
          pkg: cmd/hack-browser-data
          targets: windows/amd64,windows/386,linux/386,linux/amd64,linux/arm,linux/arm64,darwin/amd64
          # targets: windows/amd64,windows/386,darwin/amd64,linux/arm
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default 

      - name: Set Variable
        run: |
          echo "RELEASE_WIN32=browserviewer-${{ github.event.release.tag_name}}windows-32bit" >> $GITHUB_ENV
          echo "RELEASE_WIN64=browserviewer-${{ github.event.release.tag_name}}windows-64bit" >> $GITHUB_ENV
          echo "RELEASE_OSX=browserviewer-${{ github.event.release.tag_name}}osx-64bit" >> $GITHUB_ENV
          echo "RELEASE_LinuxARM=browserviewer-${{ github.event.release.tag_name}}linux-arm" >> $GITHUB_ENV
          echo "RELEASE_Linux386=browserviewer-${{ github.event.release.tag_name}}linux-386" >> $GITHUB_ENV
          echo "RELEASE_LinuxARM64=browserviewer-${{ github.event.release.tag_name}}linux-arm64" >> $GITHUB_ENV
          echo "RELEASE_LinuxAMD64=browserviewer-${{ github.event.release.tag_name}}linux-amd64" >> $GITHUB_ENV
      - name: Build zip
        run: |
          mv build/browserviewer-windows*386.exe "$RELEASE_WIN32".exe
          mv build/browserviewer-windows*amd64.exe "$RELEASE_WIN64".exe
          mv build/browserviewer-darwin-*amd64 "$RELEASE_OSX"
          mv build/browserviewer-linux-*arm-* "$RELEASE_LinuxARM"
          mv build/browserviewer-linux-*arm64 "$RELEASE_LinuxARM64"
          mv build/browserviewer-linux-*386 "$RELEASE_Linux386"
          mv build/browserviewer-linux-*amd64 "$RELEASE_LinuxAMD64"
          zip "$RELEASE_WIN32".zip "$RELEASE_WIN32".exe
          zip "$RELEASE_WIN64".zip "$RELEASE_WIN64".exe
          zip "$RELEASE_OSX".zip "$RELEASE_OSX"
          zip "$RELEASE_LinuxARM".zip "$RELEASE_LinuxARM"
          zip "$RELEASE_Linux386".zip "$RELEASE_Linux386"
          zip "$RELEASE_LinuxAMD64".zip "$RELEASE_LinuxAMD64"
          zip "$RELEASE_LinuxARM64".zip "$RELEASE_Linux386"


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:  v1.0.0
          release_name: Release  v1.0.0
          body: |
            Changes in this Release
          draft: false
          prerelease: false

      - name: Upload Release - Windows 64bit
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.RELEASE_WIN64 }}.zip
          asset_name: ${{ env.RELEASE_WIN64 }}.zip
          asset_content_type: application/zip

      - name: Upload Release - Windows 32bit
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.RELEASE_WIN32 }}.zip
          asset_name: ${{ env.RELEASE_WIN32 }}.zip
          asset_content_type: application/zip

      - name: Upload Release - Darwin amd64
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.RELEASE_OSX }}.zip
          asset_name: ${{ env.RELEASE_OSX }}.zip
          asset_content_type: application/zip

      - name: Upload Release - Linux arm
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.RELEASE_LinuxARM }}.zip
          asset_name: ${{ env.RELEASE_LinuxARM }}.zip
          asset_content_type: application/zip

      - name: Upload Release - Linux amd64
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.RELEASE_LinuxAMD64 }}.zip
          asset_name: ${{ env.RELEASE_LinuxAMD64 }}.zip
          asset_content_type: application/zip

      - name: Upload Release - Linux 386
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.RELEASE_Linux386 }}.zip
          asset_name: ${{ env.RELEASE_Linux386 }}.zip
          asset_content_type: application/zip

      - name: Upload Release - Linux arm64
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: ${{ env.RELEASE_LinuxARM64 }}.zip
          asset_content_type: application/zip
          asset_path: ./${{ env.RELEASE_LinuxARM64 }}.zip
